Outlaw_name = input("Please enter the Outlaw's name: ")
known_alias = input("Please enter the Known Alias (e.g., “The Ghost Rider”): ")
crime_committed = input("Please enter the Crime Committed(e.g., “Train Robbery”): ")
last_seen_location = input("Please enter the Last Seen Location: ")
reward_amount = int(input("Please enter the Reward Amounte: "))
print("*"*40)
print(f"\nWANTED: DEAD OR ALIVE")
print("*"*40)
print()
print(f"Name: {Outlaw_name}")
print(f"\nAlias: {known_alias}")
print()
print(f"Wanted for: {crime_committed}")
print(f"\nLast seen: {last_seen_location}") 
print()
print("-"*40)  
print(f"\nReward: {reward_amount}$")
print("-"*40)
print(f"Issued by: The Sheriff's Office of {last_seen_location}")
print("*"*40)
