Outlaw_name = input("Please enter the Outlaw's name: ")
known_alias = input("Please enter the Known Alias: ")
crime_committed = input("Please enter the Crime Committed: ")
last_seen_location = input("Please enter the Last Seen Location: ")
reward_amount = int(input("Please enter the Reward Amounte: "))
print("*"*40)
print("WANTED: DEAD OR ALIVE".center(40))
print("*"*40)
print()
print("Name:" + Outlaw_name)
print("Alias:" + known_alias)
print()
print("Wanted for:" + crime_committed)
print("Last seen:" + last_seen_location) 
print()
print("-"*40)  
print("Reward:" + reward_amount)
print("-"*40)
print("Issued by: The Sheriff's Office of",last_seen_location)
print("*"*40)