Outlaw_name = input("Please enter the Outlaw's name: ")
known_alias = input("Please enter the Known Alias (e.g., “The Ghost Rider”): ")
crime_committed = input("Please enter the Crime Committed(e.g., “Train Robbery”): ")
last_seen_location = input("Please enter the Last Seen Location: ")
reward_amount = input("Please enter the Reward Amounte.g., “$5000”): ")
print("*"*40)
print("WANTED: DEAD OR ALIVE".center(40))
print("*"*40)
print()
print("Name:".ljust(15) + Outlaw_name)
print("Alias:".ljust(15) + known_alias)
print()
print("Wanted for:".ljust(15) + crime_committed)
print("Last seen:".ljust(15) + last_seen_location) 
print()
print("-"*40)  
print("Reward:".ljust(15) + reward_amount)
print("-"*40)
print("Issued by: The Sheriff's Office of",last_seen_location)
print("*"*40)